# Generated by Django 3.1.3 on 2020-11-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ip',
            field=models.GenericIPAddressField(default='abc'),
            preserve_default=False,
        ),
    ]
